name: CD - Terraform Apply

on:
  pull_request:
    types: [closed]
    branches:
      - "master"

jobs:
  apply:
    name: Terraform Apply
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-west-2"

      - name: Initialize Terraform
        run: terraform init
        env:
          TF_VAR_token_github: ${{ secrets.TOKEN_GITHUB }}

      - name: Apply Terraform Plan
        run: terraform apply -auto-approve
        env: prod
          TF_VAR_token_github: ${{ secrets.TOKEN_GITHUB }}
          TF_BACKEND_S3_BUCKET: ${{ secrets.TF_BACKEND_S3_BUCKET }}
          TF_BACKEND_DYNAMODB_TABLE: ${{ secrets.TF_BACKEND_DYNAMODB_TABLE }}
