name: Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        env:
          TF_VAR_token_github: ${{ secrets.TOKEN_GITHUB }}
          TF_VAR_owner: mabrar-hybytes
          TF_VAR_repository: branchprotection
        run: terraform apply -auto-approve
